apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${class_name} # Needs to be unique per namespace
  namespace: ${namespace}
spec:
  provider: azure
  secretObjects:
    - secretName: ${secret_name}
      type: kubernetes.io/tls
      data:
        - objectName: ${certificate_name}
          key: tls.key
        - objectName: ${certificate_name}
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ${identity_client_id} # Setting this to use workload identity
    keyvaultName: ${key_vault_name}
    objects: |
      array:
        - |
          objectName: ${certificate_name}
          objectType: secret
    tenantId: ${tenant_id}
